//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Renpy.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class RenpyParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, IDENT=30, STRING=31, 
		PLUS=32, MINUS=33, STAR=34, SLASH=35, LT=36, GT=37, EQ=38, NOT=39, AND=40, 
		OR=41, NE=42, LE=43, GE=44, NUMBER=45, NL=46, WS=47, LINE_COMMENT=48, 
		INDENT=49, DEDENT=50, WITH=51, FADEIN=52, FADEOUT=53, JUMP=54, CALL=55, 
		RETURN=56, MENU=57, DEFAULT=58, TRUE=59, FALSE=60;
	public const int
		RULE_block = 0, RULE_statement = 1, RULE_debug_def = 2, RULE_label_def = 3, 
		RULE_define_def = 4, RULE_scene_def = 5, RULE_pause_def = 6, RULE_play_music_def = 7, 
		RULE_stop_music_def = 8, RULE_jump_def = 9, RULE_call_def = 10, RULE_show_def = 11, 
		RULE_hide_def = 12, RULE_menu_def = 13, RULE_menu_option = 14, RULE_default_def = 15, 
		RULE_return_def = 16, RULE_dialogue = 17, RULE_narration = 18, RULE_character_ref = 19, 
		RULE_arguments = 20, RULE_argument = 21, RULE_conditional_block = 22, 
		RULE_elif_block = 23, RULE_else_block = 24, RULE_assignment = 25, RULE_expression = 26, 
		RULE_logical_or = 27, RULE_logical_and = 28, RULE_logical_not = 29, RULE_relational = 30, 
		RULE_additive = 31, RULE_multiplicative = 32, RULE_primary = 33, RULE_literal = 34;
	public static readonly string[] ruleNames = {
		"block", "statement", "debug_def", "label_def", "define_def", "scene_def", 
		"pause_def", "play_music_def", "stop_music_def", "jump_def", "call_def", 
		"show_def", "hide_def", "menu_def", "menu_option", "default_def", "return_def", 
		"dialogue", "narration", "character_ref", "arguments", "argument", "conditional_block", 
		"elif_block", "else_block", "assignment", "expression", "logical_or", 
		"logical_and", "logical_not", "relational", "additive", "multiplicative", 
		"primary", "literal"
	};

	private static readonly string[] _LiteralNames = {
		null, "'debug'", "'label'", "':'", "'define'", "'='", "'scene'", "'with'", 
		"'dissolve'", "'fade'", "'crossfade'", "'pause'", "'play sound'", "'fadein'", 
		"'stop sound'", "'fadeout'", "'jump'", "'call'", "'show'", "'hide'", "'menu'", 
		"'default'", "'return'", "'('", "','", "')'", "'if'", "'elif'", "'else'", 
		"'$'", null, null, "'+'", "'-'", "'*'", "'/'", "'<'", "'>'", "'=='", "'not'", 
		"'and'", "'or'", "'!='", "'<='", "'>='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "IDENT", "STRING", "PLUS", "MINUS", 
		"STAR", "SLASH", "LT", "GT", "EQ", "NOT", "AND", "OR", "NE", "LE", "GE", 
		"NUMBER", "NL", "WS", "LINE_COMMENT", "INDENT", "DEDENT", "WITH", "FADEIN", 
		"FADEOUT", "JUMP", "CALL", "RETURN", "MENU", "DEFAULT", "TRUE", "FALSE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Renpy.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RenpyParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public RenpyParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public RenpyParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NL() { return GetTokens(RenpyParser.NL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL(int i) {
			return GetToken(RenpyParser.NL, i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 0, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			statement();
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 70372577728598L) != 0)) {
				{
				{
				State = 74;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==NL) {
					{
					{
					State = 71;
					Match(NL);
					}
					}
					State = 76;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 77;
				statement();
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Label_defContext label_def() {
			return GetRuleContext<Label_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Define_defContext define_def() {
			return GetRuleContext<Define_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Scene_defContext scene_def() {
			return GetRuleContext<Scene_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pause_defContext pause_def() {
			return GetRuleContext<Pause_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Play_music_defContext play_music_def() {
			return GetRuleContext<Play_music_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Stop_music_defContext stop_music_def() {
			return GetRuleContext<Stop_music_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Jump_defContext jump_def() {
			return GetRuleContext<Jump_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Call_defContext call_def() {
			return GetRuleContext<Call_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Menu_defContext menu_def() {
			return GetRuleContext<Menu_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Default_defContext default_def() {
			return GetRuleContext<Default_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Show_defContext show_def() {
			return GetRuleContext<Show_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Hide_defContext hide_def() {
			return GetRuleContext<Hide_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Return_defContext return_def() {
			return GetRuleContext<Return_defContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DialogueContext dialogue() {
			return GetRuleContext<DialogueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NarrationContext narration() {
			return GetRuleContext<NarrationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Conditional_blockContext conditional_block() {
			return GetRuleContext<Conditional_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Debug_defContext debug_def() {
			return GetRuleContext<Debug_defContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 101;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 83;
				label_def();
				}
				break;
			case T__3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 84;
				define_def();
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 3);
				{
				State = 85;
				scene_def();
				}
				break;
			case T__10:
				EnterOuterAlt(_localctx, 4);
				{
				State = 86;
				pause_def();
				}
				break;
			case T__11:
				EnterOuterAlt(_localctx, 5);
				{
				State = 87;
				play_music_def();
				}
				break;
			case T__13:
				EnterOuterAlt(_localctx, 6);
				{
				State = 88;
				stop_music_def();
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 7);
				{
				State = 89;
				jump_def();
				}
				break;
			case T__16:
				EnterOuterAlt(_localctx, 8);
				{
				State = 90;
				call_def();
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 9);
				{
				State = 91;
				menu_def();
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 10);
				{
				State = 92;
				default_def();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 11);
				{
				State = 93;
				show_def();
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 12);
				{
				State = 94;
				hide_def();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 13);
				{
				State = 95;
				return_def();
				}
				break;
			case T__28:
				EnterOuterAlt(_localctx, 14);
				{
				State = 96;
				assignment();
				}
				break;
			case IDENT:
				EnterOuterAlt(_localctx, 15);
				{
				State = 97;
				dialogue();
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 16);
				{
				State = 98;
				narration();
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 17);
				{
				State = 99;
				conditional_block();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 18);
				{
				State = 100;
				debug_def();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Debug_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Debug_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_debug_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterDebug_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitDebug_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDebug_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Debug_defContext debug_def() {
		Debug_defContext _localctx = new Debug_defContext(Context, State);
		EnterRule(_localctx, 4, RULE_debug_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(T__0);
			State = 104;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Label_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		public Label_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_label_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterLabel_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitLabel_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLabel_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Label_defContext label_def() {
		Label_defContext _localctx = new Label_defContext(Context, State);
		EnterRule(_localctx, 6, RULE_label_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(T__1);
			State = 107;
			Match(IDENT);
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__22) {
				{
				State = 108;
				arguments();
				}
			}

			State = 111;
			Match(T__2);
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==INDENT) {
				{
				State = 112;
				Match(INDENT);
				State = 113;
				block();
				State = 114;
				Match(DEDENT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Define_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(RenpyParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(RenpyParser.IDENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public Define_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_define_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterDefine_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitDefine_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefine_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Define_defContext define_def() {
		Define_defContext _localctx = new Define_defContext(Context, State);
		EnterRule(_localctx, 8, RULE_define_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(T__3);
			State = 119;
			Match(IDENT);
			State = 120;
			Match(T__4);
			State = 121;
			Match(IDENT);
			State = 122;
			arguments();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Scene_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		public Scene_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scene_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterScene_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitScene_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScene_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Scene_defContext scene_def() {
		Scene_defContext _localctx = new Scene_defContext(Context, State);
		EnterRule(_localctx, 10, RULE_scene_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			Match(T__5);
			State = 125;
			Match(IDENT);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 126;
				Match(T__6);
				State = 127;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1792L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pause_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RenpyParser.NUMBER, 0); }
		public Pause_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pause_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterPause_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitPause_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPause_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pause_defContext pause_def() {
		Pause_defContext _localctx = new Pause_defContext(Context, State);
		EnterRule(_localctx, 12, RULE_pause_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			Match(T__10);
			State = 131;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Play_music_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RenpyParser.NUMBER, 0); }
		public Play_music_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_play_music_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterPlay_music_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitPlay_music_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlay_music_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Play_music_defContext play_music_def() {
		Play_music_defContext _localctx = new Play_music_defContext(Context, State);
		EnterRule(_localctx, 14, RULE_play_music_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			Match(T__11);
			State = 134;
			Match(IDENT);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__12) {
				{
				State = 135;
				Match(T__12);
				State = 136;
				Match(NUMBER);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stop_music_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RenpyParser.NUMBER, 0); }
		public Stop_music_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stop_music_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterStop_music_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitStop_music_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStop_music_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Stop_music_defContext stop_music_def() {
		Stop_music_defContext _localctx = new Stop_music_defContext(Context, State);
		EnterRule(_localctx, 16, RULE_stop_music_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			Match(T__13);
			State = 140;
			Match(IDENT);
			State = 143;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__14) {
				{
				State = 141;
				Match(T__14);
				State = 142;
				Match(NUMBER);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Jump_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public Jump_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jump_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterJump_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitJump_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJump_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Jump_defContext jump_def() {
		Jump_defContext _localctx = new Jump_defContext(Context, State);
		EnterRule(_localctx, 18, RULE_jump_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			Match(T__15);
			State = 146;
			Match(IDENT);
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__22) {
				{
				State = 147;
				arguments();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Call_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public Call_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterCall_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitCall_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Call_defContext call_def() {
		Call_defContext _localctx = new Call_defContext(Context, State);
		EnterRule(_localctx, 20, RULE_call_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			Match(T__16);
			State = 151;
			Match(IDENT);
			State = 153;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__22) {
				{
				State = 152;
				arguments();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Show_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(RenpyParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(RenpyParser.IDENT, i);
		}
		public Show_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_show_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterShow_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitShow_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitShow_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Show_defContext show_def() {
		Show_defContext _localctx = new Show_defContext(Context, State);
		EnterRule(_localctx, 22, RULE_show_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			Match(T__17);
			State = 156;
			Match(IDENT);
			State = 158;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 157;
				Match(IDENT);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Hide_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public Hide_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hide_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterHide_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitHide_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHide_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Hide_defContext hide_def() {
		Hide_defContext _localctx = new Hide_defContext(Context, State);
		EnterRule(_localctx, 24, RULE_hide_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160;
			Match(T__18);
			State = 161;
			Match(IDENT);
			State = 163;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__22) {
				{
				State = 162;
				arguments();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Menu_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RenpyParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Character_refContext character_ref() {
			return GetRuleContext<Character_refContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Menu_optionContext[] menu_option() {
			return GetRuleContexts<Menu_optionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Menu_optionContext menu_option(int i) {
			return GetRuleContext<Menu_optionContext>(i);
		}
		public Menu_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_menu_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterMenu_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitMenu_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMenu_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Menu_defContext menu_def() {
		Menu_defContext _localctx = new Menu_defContext(Context, State);
		EnterRule(_localctx, 26, RULE_menu_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 165;
			Match(T__19);
			State = 167;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENT) {
				{
				State = 166;
				character_ref();
				}
			}

			State = 169;
			Match(STRING);
			State = 170;
			Match(T__2);
			State = 171;
			Match(INDENT);
			State = 175;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==STRING) {
				{
				{
				State = 172;
				menu_option();
				}
				}
				State = 177;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 178;
			Match(DEDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Menu_optionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RenpyParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		public Menu_optionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_menu_option; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterMenu_option(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitMenu_option(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMenu_option(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Menu_optionContext menu_option() {
		Menu_optionContext _localctx = new Menu_optionContext(Context, State);
		EnterRule(_localctx, 28, RULE_menu_option);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			Match(STRING);
			State = 181;
			Match(T__2);
			State = 182;
			Match(INDENT);
			State = 183;
			block();
			State = 184;
			Match(DEDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Default_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Default_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_default_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterDefault_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitDefault_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefault_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Default_defContext default_def() {
		Default_defContext _localctx = new Default_defContext(Context, State);
		EnterRule(_localctx, 30, RULE_default_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			Match(T__20);
			State = 187;
			Match(IDENT);
			State = 188;
			Match(T__4);
			State = 189;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_defContext : ParserRuleContext {
		public Return_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterReturn_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitReturn_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturn_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Return_defContext return_def() {
		Return_defContext _localctx = new Return_defContext(Context, State);
		EnterRule(_localctx, 32, RULE_return_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			Match(T__21);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DialogueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Character_refContext character_ref() {
			return GetRuleContext<Character_refContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RenpyParser.STRING, 0); }
		public DialogueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dialogue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterDialogue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitDialogue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDialogue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DialogueContext dialogue() {
		DialogueContext _localctx = new DialogueContext(Context, State);
		EnterRule(_localctx, 34, RULE_dialogue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			character_ref();
			State = 194;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NarrationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RenpyParser.STRING, 0); }
		public NarrationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_narration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterNarration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitNarration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNarration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NarrationContext narration() {
		NarrationContext _localctx = new NarrationContext(Context, State);
		EnterRule(_localctx, 36, RULE_narration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Character_refContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		public Character_refContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_character_ref; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterCharacter_ref(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitCharacter_ref(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCharacter_ref(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Character_refContext character_ref() {
		Character_refContext _localctx = new Character_refContext(Context, State);
		EnterRule(_localctx, 38, RULE_character_ref);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			Match(IDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		public ArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arguments; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterArguments(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitArguments(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsContext arguments() {
		ArgumentsContext _localctx = new ArgumentsContext(Context, State);
		EnterRule(_localctx, 40, RULE_arguments);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			Match(T__22);
			State = 201;
			argument();
			State = 206;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__23) {
				{
				{
				State = 202;
				Match(T__23);
				State = 203;
				argument();
				}
				}
				State = 208;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 209;
			Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 42, RULE_argument);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 213;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				{
				State = 211;
				Match(IDENT);
				State = 212;
				Match(T__4);
				}
				break;
			}
			State = 215;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Conditional_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Elif_blockContext[] elif_block() {
			return GetRuleContexts<Elif_blockContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Elif_blockContext elif_block(int i) {
			return GetRuleContext<Elif_blockContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Else_blockContext else_block() {
			return GetRuleContext<Else_blockContext>(0);
		}
		public Conditional_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditional_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterConditional_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitConditional_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditional_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Conditional_blockContext conditional_block() {
		Conditional_blockContext _localctx = new Conditional_blockContext(Context, State);
		EnterRule(_localctx, 44, RULE_conditional_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 217;
			Match(T__25);
			State = 218;
			expression();
			State = 219;
			Match(T__2);
			State = 220;
			Match(INDENT);
			State = 221;
			block();
			State = 222;
			Match(DEDENT);
			State = 226;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__26) {
				{
				{
				State = 223;
				elif_block();
				}
				}
				State = 228;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 230;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__27) {
				{
				State = 229;
				else_block();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Elif_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		public Elif_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elif_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterElif_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitElif_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElif_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Elif_blockContext elif_block() {
		Elif_blockContext _localctx = new Elif_blockContext(Context, State);
		EnterRule(_localctx, 46, RULE_elif_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232;
			Match(T__26);
			State = 233;
			expression();
			State = 234;
			Match(T__2);
			State = 235;
			Match(INDENT);
			State = 236;
			block();
			State = 237;
			Match(DEDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Else_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(RenpyParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(RenpyParser.DEDENT, 0); }
		public Else_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_else_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterElse_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitElse_block(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElse_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Else_blockContext else_block() {
		Else_blockContext _localctx = new Else_blockContext(Context, State);
		EnterRule(_localctx, 48, RULE_else_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239;
			Match(T__27);
			State = 240;
			Match(T__2);
			State = 241;
			Match(INDENT);
			State = 242;
			block();
			State = 243;
			Match(DEDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 50, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			Match(T__28);
			State = 246;
			Match(IDENT);
			State = 247;
			Match(T__4);
			State = 248;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveContext additive() {
			return GetRuleContext<AdditiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logical_orContext logical_or() {
			return GetRuleContext<Logical_orContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 52, RULE_expression);
		try {
			State = 252;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 250;
				additive();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 251;
				logical_or();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logical_orContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Logical_andContext[] logical_and() {
			return GetRuleContexts<Logical_andContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logical_andContext logical_and(int i) {
			return GetRuleContext<Logical_andContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(RenpyParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(RenpyParser.OR, i);
		}
		public Logical_orContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logical_or; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterLogical_or(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitLogical_or(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogical_or(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logical_orContext logical_or() {
		Logical_orContext _localctx = new Logical_orContext(Context, State);
		EnterRule(_localctx, 54, RULE_logical_or);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			logical_and();
			State = 259;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 255;
				Match(OR);
				State = 256;
				logical_and();
				}
				}
				State = 261;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logical_andContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Logical_notContext[] logical_not() {
			return GetRuleContexts<Logical_notContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logical_notContext logical_not(int i) {
			return GetRuleContext<Logical_notContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(RenpyParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(RenpyParser.AND, i);
		}
		public Logical_andContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logical_and; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterLogical_and(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitLogical_and(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogical_and(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logical_andContext logical_and() {
		Logical_andContext _localctx = new Logical_andContext(Context, State);
		EnterRule(_localctx, 56, RULE_logical_and);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262;
			logical_not();
			State = 267;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==AND) {
				{
				{
				State = 263;
				Match(AND);
				State = 264;
				logical_not();
				}
				}
				State = 269;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logical_notContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(RenpyParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Logical_notContext logical_not() {
			return GetRuleContext<Logical_notContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationalContext relational() {
			return GetRuleContext<RelationalContext>(0);
		}
		public Logical_notContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logical_not; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterLogical_not(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitLogical_not(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogical_not(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logical_notContext logical_not() {
		Logical_notContext _localctx = new Logical_notContext(Context, State);
		EnterRule(_localctx, 58, RULE_logical_not);
		try {
			State = 273;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NOT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 270;
				Match(NOT);
				State = 271;
				logical_not();
				}
				break;
			case T__22:
			case IDENT:
			case STRING:
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 272;
				relational();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalContext : ParserRuleContext {
		public IToken _LT;
		public IList<IToken> _op = new List<IToken>();
		public IToken _GT;
		public IToken _LE;
		public IToken _GE;
		public IToken _EQ;
		public IToken _NE;
		public IToken _tset583;
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveContext[] additive() {
			return GetRuleContexts<AdditiveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveContext additive(int i) {
			return GetRuleContext<AdditiveContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LT() { return GetTokens(RenpyParser.LT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT(int i) {
			return GetToken(RenpyParser.LT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GT() { return GetTokens(RenpyParser.GT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT(int i) {
			return GetToken(RenpyParser.GT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LE() { return GetTokens(RenpyParser.LE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LE(int i) {
			return GetToken(RenpyParser.LE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GE() { return GetTokens(RenpyParser.GE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GE(int i) {
			return GetToken(RenpyParser.GE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EQ() { return GetTokens(RenpyParser.EQ); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ(int i) {
			return GetToken(RenpyParser.EQ, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NE() { return GetTokens(RenpyParser.NE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NE(int i) {
			return GetToken(RenpyParser.NE, i);
		}
		public RelationalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relational; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterRelational(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitRelational(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelational(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalContext relational() {
		RelationalContext _localctx = new RelationalContext(Context, State);
		EnterRule(_localctx, 60, RULE_relational);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 275;
			additive();
			State = 280;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 31267361914880L) != 0)) {
				{
				{
				State = 276;
				_localctx._tset583 = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 31267361914880L) != 0)) ) {
					_localctx._tset583 = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				_localctx._op.Add(_localctx._tset583);
				State = 277;
				additive();
				}
				}
				State = 282;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AdditiveContext : ParserRuleContext {
		public IToken _PLUS;
		public IList<IToken> _op = new List<IToken>();
		public IToken _MINUS;
		public IToken _tset622;
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeContext[] multiplicative() {
			return GetRuleContexts<MultiplicativeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeContext multiplicative(int i) {
			return GetRuleContext<MultiplicativeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(RenpyParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(RenpyParser.PLUS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MINUS() { return GetTokens(RenpyParser.MINUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS(int i) {
			return GetToken(RenpyParser.MINUS, i);
		}
		public AdditiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additive; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterAdditive(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitAdditive(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditive(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveContext additive() {
		AdditiveContext _localctx = new AdditiveContext(Context, State);
		EnterRule(_localctx, 62, RULE_additive);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			multiplicative();
			State = 288;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 284;
				_localctx._tset622 = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
					_localctx._tset622 = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				_localctx._op.Add(_localctx._tset622);
				State = 285;
				multiplicative();
				}
				}
				State = 290;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplicativeContext : ParserRuleContext {
		public IToken _STAR;
		public IList<IToken> _op = new List<IToken>();
		public IToken _SLASH;
		public IToken _tset645;
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryContext[] primary() {
			return GetRuleContexts<PrimaryContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryContext primary(int i) {
			return GetRuleContext<PrimaryContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STAR() { return GetTokens(RenpyParser.STAR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STAR(int i) {
			return GetToken(RenpyParser.STAR, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SLASH() { return GetTokens(RenpyParser.SLASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH(int i) {
			return GetToken(RenpyParser.SLASH, i);
		}
		public MultiplicativeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicative; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterMultiplicative(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitMultiplicative(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicative(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeContext multiplicative() {
		MultiplicativeContext _localctx = new MultiplicativeContext(Context, State);
		EnterRule(_localctx, 64, RULE_multiplicative);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 291;
			primary();
			State = 296;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==STAR || _la==SLASH) {
				{
				{
				State = 292;
				_localctx._tset645 = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==STAR || _la==SLASH) ) {
					_localctx._tset645 = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				_localctx._op.Add(_localctx._tset645);
				State = 293;
				primary();
				}
				}
				State = 298;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public PrimaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primary; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterPrimary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitPrimary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimary(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryContext primary() {
		PrimaryContext _localctx = new PrimaryContext(Context, State);
		EnterRule(_localctx, 66, RULE_primary);
		try {
			State = 304;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENT:
			case STRING:
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 299;
				literal();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 2);
				{
				State = 300;
				Match(T__22);
				State = 301;
				expression();
				State = 302;
				Match(T__24);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RenpyParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RenpyParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(RenpyParser.IDENT, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IRenpyListener typedListener = listener as IRenpyListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRenpyVisitor<TResult> typedVisitor = visitor as IRenpyVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 68, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 306;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 35187593314304L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,60,309,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,1,0,1,0,5,
		0,73,8,0,10,0,12,0,76,9,0,1,0,5,0,79,8,0,10,0,12,0,82,9,0,1,1,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,102,8,
		1,1,2,1,2,1,2,1,3,1,3,1,3,3,3,110,8,3,1,3,1,3,1,3,1,3,1,3,3,3,117,8,3,
		1,4,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,3,5,129,8,5,1,6,1,6,1,6,1,7,1,
		7,1,7,1,7,3,7,138,8,7,1,8,1,8,1,8,1,8,3,8,144,8,8,1,9,1,9,1,9,3,9,149,
		8,9,1,10,1,10,1,10,3,10,154,8,10,1,11,1,11,1,11,3,11,159,8,11,1,12,1,12,
		1,12,3,12,164,8,12,1,13,1,13,3,13,168,8,13,1,13,1,13,1,13,1,13,5,13,174,
		8,13,10,13,12,13,177,9,13,1,13,1,13,1,14,1,14,1,14,1,14,1,14,1,14,1,15,
		1,15,1,15,1,15,1,15,1,16,1,16,1,17,1,17,1,17,1,18,1,18,1,19,1,19,1,20,
		1,20,1,20,1,20,5,20,205,8,20,10,20,12,20,208,9,20,1,20,1,20,1,21,1,21,
		3,21,214,8,21,1,21,1,21,1,22,1,22,1,22,1,22,1,22,1,22,1,22,5,22,225,8,
		22,10,22,12,22,228,9,22,1,22,3,22,231,8,22,1,23,1,23,1,23,1,23,1,23,1,
		23,1,23,1,24,1,24,1,24,1,24,1,24,1,24,1,25,1,25,1,25,1,25,1,25,1,26,1,
		26,3,26,253,8,26,1,27,1,27,1,27,5,27,258,8,27,10,27,12,27,261,9,27,1,28,
		1,28,1,28,5,28,266,8,28,10,28,12,28,269,9,28,1,29,1,29,1,29,3,29,274,8,
		29,1,30,1,30,1,30,5,30,279,8,30,10,30,12,30,282,9,30,1,31,1,31,1,31,5,
		31,287,8,31,10,31,12,31,290,9,31,1,32,1,32,1,32,5,32,295,8,32,10,32,12,
		32,298,9,32,1,33,1,33,1,33,1,33,1,33,3,33,305,8,33,1,34,1,34,1,34,0,0,
		35,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,
		48,50,52,54,56,58,60,62,64,66,68,0,5,1,0,8,10,2,0,36,38,42,44,1,0,32,33,
		1,0,34,35,2,0,30,31,45,45,315,0,70,1,0,0,0,2,101,1,0,0,0,4,103,1,0,0,0,
		6,106,1,0,0,0,8,118,1,0,0,0,10,124,1,0,0,0,12,130,1,0,0,0,14,133,1,0,0,
		0,16,139,1,0,0,0,18,145,1,0,0,0,20,150,1,0,0,0,22,155,1,0,0,0,24,160,1,
		0,0,0,26,165,1,0,0,0,28,180,1,0,0,0,30,186,1,0,0,0,32,191,1,0,0,0,34,193,
		1,0,0,0,36,196,1,0,0,0,38,198,1,0,0,0,40,200,1,0,0,0,42,213,1,0,0,0,44,
		217,1,0,0,0,46,232,1,0,0,0,48,239,1,0,0,0,50,245,1,0,0,0,52,252,1,0,0,
		0,54,254,1,0,0,0,56,262,1,0,0,0,58,273,1,0,0,0,60,275,1,0,0,0,62,283,1,
		0,0,0,64,291,1,0,0,0,66,304,1,0,0,0,68,306,1,0,0,0,70,80,3,2,1,0,71,73,
		5,46,0,0,72,71,1,0,0,0,73,76,1,0,0,0,74,72,1,0,0,0,74,75,1,0,0,0,75,77,
		1,0,0,0,76,74,1,0,0,0,77,79,3,2,1,0,78,74,1,0,0,0,79,82,1,0,0,0,80,78,
		1,0,0,0,80,81,1,0,0,0,81,1,1,0,0,0,82,80,1,0,0,0,83,102,3,6,3,0,84,102,
		3,8,4,0,85,102,3,10,5,0,86,102,3,12,6,0,87,102,3,14,7,0,88,102,3,16,8,
		0,89,102,3,18,9,0,90,102,3,20,10,0,91,102,3,26,13,0,92,102,3,30,15,0,93,
		102,3,22,11,0,94,102,3,24,12,0,95,102,3,32,16,0,96,102,3,50,25,0,97,102,
		3,34,17,0,98,102,3,36,18,0,99,102,3,44,22,0,100,102,3,4,2,0,101,83,1,0,
		0,0,101,84,1,0,0,0,101,85,1,0,0,0,101,86,1,0,0,0,101,87,1,0,0,0,101,88,
		1,0,0,0,101,89,1,0,0,0,101,90,1,0,0,0,101,91,1,0,0,0,101,92,1,0,0,0,101,
		93,1,0,0,0,101,94,1,0,0,0,101,95,1,0,0,0,101,96,1,0,0,0,101,97,1,0,0,0,
		101,98,1,0,0,0,101,99,1,0,0,0,101,100,1,0,0,0,102,3,1,0,0,0,103,104,5,
		1,0,0,104,105,3,52,26,0,105,5,1,0,0,0,106,107,5,2,0,0,107,109,5,30,0,0,
		108,110,3,40,20,0,109,108,1,0,0,0,109,110,1,0,0,0,110,111,1,0,0,0,111,
		116,5,3,0,0,112,113,5,49,0,0,113,114,3,0,0,0,114,115,5,50,0,0,115,117,
		1,0,0,0,116,112,1,0,0,0,116,117,1,0,0,0,117,7,1,0,0,0,118,119,5,4,0,0,
		119,120,5,30,0,0,120,121,5,5,0,0,121,122,5,30,0,0,122,123,3,40,20,0,123,
		9,1,0,0,0,124,125,5,6,0,0,125,128,5,30,0,0,126,127,5,7,0,0,127,129,7,0,
		0,0,128,126,1,0,0,0,128,129,1,0,0,0,129,11,1,0,0,0,130,131,5,11,0,0,131,
		132,5,45,0,0,132,13,1,0,0,0,133,134,5,12,0,0,134,137,5,30,0,0,135,136,
		5,13,0,0,136,138,5,45,0,0,137,135,1,0,0,0,137,138,1,0,0,0,138,15,1,0,0,
		0,139,140,5,14,0,0,140,143,5,30,0,0,141,142,5,15,0,0,142,144,5,45,0,0,
		143,141,1,0,0,0,143,144,1,0,0,0,144,17,1,0,0,0,145,146,5,16,0,0,146,148,
		5,30,0,0,147,149,3,40,20,0,148,147,1,0,0,0,148,149,1,0,0,0,149,19,1,0,
		0,0,150,151,5,17,0,0,151,153,5,30,0,0,152,154,3,40,20,0,153,152,1,0,0,
		0,153,154,1,0,0,0,154,21,1,0,0,0,155,156,5,18,0,0,156,158,5,30,0,0,157,
		159,5,30,0,0,158,157,1,0,0,0,158,159,1,0,0,0,159,23,1,0,0,0,160,161,5,
		19,0,0,161,163,5,30,0,0,162,164,3,40,20,0,163,162,1,0,0,0,163,164,1,0,
		0,0,164,25,1,0,0,0,165,167,5,20,0,0,166,168,3,38,19,0,167,166,1,0,0,0,
		167,168,1,0,0,0,168,169,1,0,0,0,169,170,5,31,0,0,170,171,5,3,0,0,171,175,
		5,49,0,0,172,174,3,28,14,0,173,172,1,0,0,0,174,177,1,0,0,0,175,173,1,0,
		0,0,175,176,1,0,0,0,176,178,1,0,0,0,177,175,1,0,0,0,178,179,5,50,0,0,179,
		27,1,0,0,0,180,181,5,31,0,0,181,182,5,3,0,0,182,183,5,49,0,0,183,184,3,
		0,0,0,184,185,5,50,0,0,185,29,1,0,0,0,186,187,5,21,0,0,187,188,5,30,0,
		0,188,189,5,5,0,0,189,190,3,52,26,0,190,31,1,0,0,0,191,192,5,22,0,0,192,
		33,1,0,0,0,193,194,3,38,19,0,194,195,5,31,0,0,195,35,1,0,0,0,196,197,5,
		31,0,0,197,37,1,0,0,0,198,199,5,30,0,0,199,39,1,0,0,0,200,201,5,23,0,0,
		201,206,3,42,21,0,202,203,5,24,0,0,203,205,3,42,21,0,204,202,1,0,0,0,205,
		208,1,0,0,0,206,204,1,0,0,0,206,207,1,0,0,0,207,209,1,0,0,0,208,206,1,
		0,0,0,209,210,5,25,0,0,210,41,1,0,0,0,211,212,5,30,0,0,212,214,5,5,0,0,
		213,211,1,0,0,0,213,214,1,0,0,0,214,215,1,0,0,0,215,216,3,52,26,0,216,
		43,1,0,0,0,217,218,5,26,0,0,218,219,3,52,26,0,219,220,5,3,0,0,220,221,
		5,49,0,0,221,222,3,0,0,0,222,226,5,50,0,0,223,225,3,46,23,0,224,223,1,
		0,0,0,225,228,1,0,0,0,226,224,1,0,0,0,226,227,1,0,0,0,227,230,1,0,0,0,
		228,226,1,0,0,0,229,231,3,48,24,0,230,229,1,0,0,0,230,231,1,0,0,0,231,
		45,1,0,0,0,232,233,5,27,0,0,233,234,3,52,26,0,234,235,5,3,0,0,235,236,
		5,49,0,0,236,237,3,0,0,0,237,238,5,50,0,0,238,47,1,0,0,0,239,240,5,28,
		0,0,240,241,5,3,0,0,241,242,5,49,0,0,242,243,3,0,0,0,243,244,5,50,0,0,
		244,49,1,0,0,0,245,246,5,29,0,0,246,247,5,30,0,0,247,248,5,5,0,0,248,249,
		3,52,26,0,249,51,1,0,0,0,250,253,3,62,31,0,251,253,3,54,27,0,252,250,1,
		0,0,0,252,251,1,0,0,0,253,53,1,0,0,0,254,259,3,56,28,0,255,256,5,41,0,
		0,256,258,3,56,28,0,257,255,1,0,0,0,258,261,1,0,0,0,259,257,1,0,0,0,259,
		260,1,0,0,0,260,55,1,0,0,0,261,259,1,0,0,0,262,267,3,58,29,0,263,264,5,
		40,0,0,264,266,3,58,29,0,265,263,1,0,0,0,266,269,1,0,0,0,267,265,1,0,0,
		0,267,268,1,0,0,0,268,57,1,0,0,0,269,267,1,0,0,0,270,271,5,39,0,0,271,
		274,3,58,29,0,272,274,3,60,30,0,273,270,1,0,0,0,273,272,1,0,0,0,274,59,
		1,0,0,0,275,280,3,62,31,0,276,277,7,1,0,0,277,279,3,62,31,0,278,276,1,
		0,0,0,279,282,1,0,0,0,280,278,1,0,0,0,280,281,1,0,0,0,281,61,1,0,0,0,282,
		280,1,0,0,0,283,288,3,64,32,0,284,285,7,2,0,0,285,287,3,64,32,0,286,284,
		1,0,0,0,287,290,1,0,0,0,288,286,1,0,0,0,288,289,1,0,0,0,289,63,1,0,0,0,
		290,288,1,0,0,0,291,296,3,66,33,0,292,293,7,3,0,0,293,295,3,66,33,0,294,
		292,1,0,0,0,295,298,1,0,0,0,296,294,1,0,0,0,296,297,1,0,0,0,297,65,1,0,
		0,0,298,296,1,0,0,0,299,305,3,68,34,0,300,301,5,23,0,0,301,302,3,52,26,
		0,302,303,5,25,0,0,303,305,1,0,0,0,304,299,1,0,0,0,304,300,1,0,0,0,305,
		67,1,0,0,0,306,307,7,4,0,0,307,69,1,0,0,0,26,74,80,101,109,116,128,137,
		143,148,153,158,163,167,175,206,213,226,230,252,259,267,273,280,288,296,
		304
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
